# Generated by Django 3.1.7 on 2021-04-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210326_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_title', models.CharField(default='Title', max_length=100)),
                ('survey_description', models.CharField(default='Description', max_length=500)),
                ('survey_reward', models.IntegerField(default=500)),
                ('survey_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('survey_updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
